experiment:
  name: lightglu3d_uniSoftMax
  seed: 0

model:
  name: lightglu3d_uniSoftMax
  weights: "/home/x_jiagu/glue-factory/superpoint_lightglue.pth"
  input_dim: 256
  descriptor_dim: 256
  n_layers: 9
  num_heads: 4
  flash: True
  checkpointed: True
  mp: True
  filter_threshold: 0.1
  loss:
    gamma: 1.0
    fn: nll
    nll_balancing: 0.5
  3d_rotation_aug: True

data:
  name: mega_2d3d_dataset_soft_fix_pad
  root: "/proj/vlarsson/outputs"
  split_train: "splits/train_scenes_clean.txt"
  split_val: "splits/val.txt"
  split_test: "splits/test.txt"
  batch_size: 32
  num_workers: 12
  pos_reproj_thresh: 3.0
  neg_reproj_thresh: 8.0

train:
  seed: 0
  epochs: 30
  optimizer: adamw
  lr: 1e-5 
  lr_schedule:
    type: "exp" 
    start: 15
    on_epoch: True
    exp_div_10: 45 # gamma = 0.95
  lr_scaling: [
    [0.0, ["token_confidence."]], # freeze confidence classifier first
    [0.1, ["self_attn.", "posenc.","cross_attn.to_qk2d", "cross_attn.to_v2d"]],
    [100, ["dampingnet.const"]]
    ]
  freeze_2d: False
  initial_3d_with_2d: True
  log_every_iter: 50    
  eval_every_iter: 200
  save_every_iter: 400

val:
  interval: 1
  recall_metrics: [1, 3, 5]
