experiment:
  name: lightglu3d
  seed: 0

model:
  name: lightglue
  weights: "/home/x_jiagu/glue-factory/superpoint_lightglue.pth"
  input_dim: 256
  descriptor_dim: 256
  n_layers: 9
  num_heads: 4
  flash: True
  checkpointed: True
  freeze_backbone: False
  mp: True
  filter_threshold: 0.1
  loss:
    gamma: 1.0
    fn: nll
    nll_balancing: 0.5

data:
  name: mega_2d3d_dataset
  root: "/proj/vlarsson/outputs"
  split_train: "/home/x_lishu/matching/glue-factory/gluefactory/datasets/megadepth_scene_lists/train_scenes_clean_try.txt"
  split_val: "/home/x_lishu/matching/glue-factory/gluefactory/datasets/megadepth_scene_lists/valid_scenes_clean_try.txt"
  split_test: "/home/x_lishu/matching/glue-factory/gluefactory/datasets/megadepth_scene_lists/test_scenes_clean_try.txt"
  batch_size: 8
  num_workers: 4

train:
  seed: 0
  epochs: 20
  optimizer: adamw
  lr: 1e-3 # 1e-4 for 3-10 epochs
  lr_schedule:
    type: "MultiStepLR" 
    on_epoch: True     
    options:
      milestones: [12, 19]
      gamma: 0.5

  log_every_iter: 50    
  eval_every_iter: 200
  save_every_iter: 400

val:
  interval: 1
  recall_metrics: [1, 3, 5]
